version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "8080:8080"
    entrypoint: sh entrypoint.sh ./server
    depends_on:
      - db

  db:
    image: "mysql:8.0"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci

volumes:
  mysql_data:
    driver: local
